// <auto-generated />
using System;
using KorepetycjeNaJuz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KorepetycjeNaJuz.Data.Migrations
{
    [DbContext(typeof(KorepetycjeContext))]
    [Migration("20181021213301_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.CoachAddresses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(1000);

                    b.Property<int>("CoachId");

                    b.Property<double?>("Latitude");

                    b.Property<double?>("Longitude");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("CoachAddresses");
                });

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.CoachLessons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoachId");

                    b.Property<int>("LessonLevelId");

                    b.Property<int>("LessonSubjectId");

                    b.Property<decimal>("RatePerHour");

                    b.Property<int?>("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("LessonLevelId");

                    b.HasIndex("SubjectId");

                    b.ToTable("CoachLessons");
                });

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.LessonLevels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LevelName")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("LessonLevels");
                });

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.Lessons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoachAddressId");

                    b.Property<int>("CoachLessonId");

                    b.Property<DateTime>("Date");

                    b.Property<int>("LessonStatusId");

                    b.Property<int>("NumberOfHours");

                    b.Property<string>("OpinionOfCoach");

                    b.Property<string>("OpinionOfStudent");

                    b.Property<byte?>("RatingOfCoach");

                    b.Property<byte?>("RatingOfStudent");

                    b.Property<int>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("CoachAddressId");

                    b.HasIndex("CoachLessonId");

                    b.HasIndex("LessonStatusId");

                    b.HasIndex("StudentId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.LessonStatuses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("LessonStatuses");
                });

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.LessonSubjects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("LessonSubjects");
                });

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfSending");

                    b.Property<string>("Message")
                        .HasMaxLength(1000);

                    b.Property<int>("OwnerId");

                    b.Property<int>("RecipientId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RecipientId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Avatar")
                        .HasMaxLength(1000);

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Email")
                        .HasMaxLength(255);

                    b.Property<string>("FirstName")
                        .HasMaxLength(255);

                    b.Property<bool>("IsCoach");

                    b.Property<string>("LastName")
                        .HasMaxLength(255);

                    b.Property<string>("Telephone")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.CoachAddresses", b =>
                {
                    b.HasOne("KorepetycjeNaJuz.Data.Models.Users", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.CoachLessons", b =>
                {
                    b.HasOne("KorepetycjeNaJuz.Data.Models.Users", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KorepetycjeNaJuz.Data.Models.LessonLevels", "LessonLevel")
                        .WithMany()
                        .HasForeignKey("LessonLevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KorepetycjeNaJuz.Data.Models.LessonSubjects", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.Lessons", b =>
                {
                    b.HasOne("KorepetycjeNaJuz.Data.Models.CoachAddresses", "CoachAddress")
                        .WithMany()
                        .HasForeignKey("CoachAddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KorepetycjeNaJuz.Data.Models.CoachLessons", "CoachLesson")
                        .WithMany()
                        .HasForeignKey("CoachLessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KorepetycjeNaJuz.Data.Models.LessonStatuses", "LessonStatus")
                        .WithMany()
                        .HasForeignKey("LessonStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KorepetycjeNaJuz.Data.Models.Users", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KorepetycjeNaJuz.Data.Models.Messages", b =>
                {
                    b.HasOne("KorepetycjeNaJuz.Data.Models.Users", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KorepetycjeNaJuz.Data.Models.Users", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
